<a href="https://colab.research.google.com/github/soumyamegha/pyrthonapplication/blob/main/codess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class myclass:
  def __init__(self,name):
     print("hello",name)
obj=myclass("soumya")

hello soumya


In [ ]:
class student:
  def __init__(self,roll,name):
    self.name="soumya"
    self.roll=71
    print(self.name,self.roll)
obj=student(71,"soumya")

soumya 71


In [ ]:
class person:
    def __init__(self):
       print("bye...")
    def mymethod(self,num):
       print("the cube of number is :",num**3)
obj_person=person()
obj_person.mymethod(4)


bye...
the cube of number is : 64


In [ ]:
class Animal:
  def speak(self):
    print("Animal Speaking")
class Dog(Animal):
  def bark(self):
    print("dog barking")
d=Dog()
d.bark()
d.speak()   

dog barking
Animal Speaking


write a python program which base class contins addition of two no.s and derive class contain multiplication of same no



In [ ]:
class base:
  def ADD(self,a,b):
   return a+b
class derive(base):  
  def MUL(self,a,b):
    return a*b
m=int(input('a = '))
n=int(input('b = '))
obj=derive()
print(obj.ADD(m,n))    
print(obj.MUL(m,n))

a = 3
b = 5
8
15


write a python programm using multilevel inheritance to design a calculator which contains four derive class and one child class


In [ ]:
class A:
  def ADD(self,a,b):
    return a+b
class S(A):
  def SUB(self,a,b):
    return a-b    
class M(S):
  def MUL(self,a,b):
    return a*b
class D(M):
  def DIV(self,a,b):
    return a/b
class E(D):
  def REM(self,a,b):
    return a%b
m=int(input(' a = '))    
n=int(input(' b = '))
d=E()
print(d.ADD(m,n))
print(d.SUB(m,n))
print(d.MUL(m,n))
print(d.DIV(m,n))
print(d.REM(m,n))

 a = 4
 b = 6
10
-2
24
0.6666666666666666
4


In [ ]:
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
import numpy
list=[10,20,30,40,50]
arr=numpy.array(list)
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
list=[10,20,30,40,50]
arr=np.array(list)
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
list=[10,20,30,40,50]
arr=np.array(list)
print('Size:',arr.size)
print('Datatype:',arr.dtype)
print('Dimension:',arr.ndim)
print('Shape:',arr.shape)

Size: 5
Datatype: int64
Dimension: 1
Shape: (5,)


In [ ]:
import numpy as np
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr[1])

[40 50 60]


In [ ]:
import numpy as np
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr[1][1])

50


In [ ]:
import numpy as np
three_dimensional_list=[[[1,2,3],[4,5,6],[7,8,9]]]
three_dimensional_arr=np.array(three_dimensional_list)
print("3D array is: ",three_dimensional_arr)

3D array is:  [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
import numpy as np
list

In [1]:
import numpy
n=int(input('enter size:'))
arr=numpy.ndarray(shape=(n),dtype=int)
print('enter %d element:'%n)
for i in range(n):
  arr[i]=int(input())
  print('array elements:',arr)
   

enter size:2
enter 2 element:
11
array elements: [             11 140503697997720]
22
array elements: [11 22]


In [4]:
import numpy
n = int (input('Enter Size:'))
arr = numpy.ndarray(shape=(n),dtype=int)
print('Enter %d element :'%n)
def oddcount(a,o):
  if a%2!=0:
    o+=1
  return o
def evencount(a,e):
  if a%2==0:
    e+=1
  return e
o=0
e=0
for i in range(n):
  arr[i]=int(input())
  o=oddcount(arr[i],o)
  e=evencount(arr[i],e)
print('Array Elements :', arr)
print(o)
print(e)

Enter Size:2
Enter 2 element :
4
5
Array Elements : [4 5]
1
1


In [5]:
import numpy as np
list=[[10,20,30,],[40,50,60],[70,80,90]]
arr=np.array(list)
print(arr)
print('Slicing...... .....')
res=arr[:,:]
print(res)


[[10 20 30]
 [40 50 60]
 [70 80 90]]
Slicing...... .....
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
str='abit is an engineering college'
print(str[0:27:5])
str1=slice(0,27,3)
str2=str[str1]
print(str2)

ai nnl
atsnnnrgo
